// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/google/uuid"
	"github.com/verifa/coastline/ent/approval"
	"github.com/verifa/coastline/ent/predicate"
	"github.com/verifa/coastline/ent/project"
	"github.com/verifa/coastline/ent/request"
	"github.com/verifa/coastline/ent/schema"
	"github.com/verifa/coastline/ent/service"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeApproval = "Approval"
	TypeProject  = "Project"
	TypeRequest  = "Request"
	TypeService  = "Service"
)

// ApprovalMutation represents an operation that mutates the Approval nodes in the graph.
type ApprovalMutation struct {
	config
	op              Op
	typ             string
	id              *uuid.UUID
	is_automated    *bool
	approver        *string
	clearedFields   map[string]struct{}
	_Request        map[uuid.UUID]struct{}
	removed_Request map[uuid.UUID]struct{}
	cleared_Request bool
	done            bool
	oldValue        func(context.Context) (*Approval, error)
	predicates      []predicate.Approval
}

var _ ent.Mutation = (*ApprovalMutation)(nil)

// approvalOption allows management of the mutation configuration using functional options.
type approvalOption func(*ApprovalMutation)

// newApprovalMutation creates new mutation for the Approval entity.
func newApprovalMutation(c config, op Op, opts ...approvalOption) *ApprovalMutation {
	m := &ApprovalMutation{
		config:        c,
		op:            op,
		typ:           TypeApproval,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withApprovalID sets the ID field of the mutation.
func withApprovalID(id uuid.UUID) approvalOption {
	return func(m *ApprovalMutation) {
		var (
			err   error
			once  sync.Once
			value *Approval
		)
		m.oldValue = func(ctx context.Context) (*Approval, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Approval.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withApproval sets the old Approval of the mutation.
func withApproval(node *Approval) approvalOption {
	return func(m *ApprovalMutation) {
		m.oldValue = func(context.Context) (*Approval, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ApprovalMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ApprovalMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Approval entities.
func (m *ApprovalMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ApprovalMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ApprovalMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Approval.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetIsAutomated sets the "is_automated" field.
func (m *ApprovalMutation) SetIsAutomated(b bool) {
	m.is_automated = &b
}

// IsAutomated returns the value of the "is_automated" field in the mutation.
func (m *ApprovalMutation) IsAutomated() (r bool, exists bool) {
	v := m.is_automated
	if v == nil {
		return
	}
	return *v, true
}

// OldIsAutomated returns the old "is_automated" field's value of the Approval entity.
// If the Approval object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApprovalMutation) OldIsAutomated(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsAutomated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsAutomated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsAutomated: %w", err)
	}
	return oldValue.IsAutomated, nil
}

// ResetIsAutomated resets all changes to the "is_automated" field.
func (m *ApprovalMutation) ResetIsAutomated() {
	m.is_automated = nil
}

// SetApprover sets the "approver" field.
func (m *ApprovalMutation) SetApprover(s string) {
	m.approver = &s
}

// Approver returns the value of the "approver" field in the mutation.
func (m *ApprovalMutation) Approver() (r string, exists bool) {
	v := m.approver
	if v == nil {
		return
	}
	return *v, true
}

// OldApprover returns the old "approver" field's value of the Approval entity.
// If the Approval object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApprovalMutation) OldApprover(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldApprover is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldApprover requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldApprover: %w", err)
	}
	return oldValue.Approver, nil
}

// ResetApprover resets all changes to the "approver" field.
func (m *ApprovalMutation) ResetApprover() {
	m.approver = nil
}

// AddRequestIDs adds the "Request" edge to the Request entity by ids.
func (m *ApprovalMutation) AddRequestIDs(ids ...uuid.UUID) {
	if m._Request == nil {
		m._Request = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m._Request[ids[i]] = struct{}{}
	}
}

// ClearRequest clears the "Request" edge to the Request entity.
func (m *ApprovalMutation) ClearRequest() {
	m.cleared_Request = true
}

// RequestCleared reports if the "Request" edge to the Request entity was cleared.
func (m *ApprovalMutation) RequestCleared() bool {
	return m.cleared_Request
}

// RemoveRequestIDs removes the "Request" edge to the Request entity by IDs.
func (m *ApprovalMutation) RemoveRequestIDs(ids ...uuid.UUID) {
	if m.removed_Request == nil {
		m.removed_Request = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m._Request, ids[i])
		m.removed_Request[ids[i]] = struct{}{}
	}
}

// RemovedRequest returns the removed IDs of the "Request" edge to the Request entity.
func (m *ApprovalMutation) RemovedRequestIDs() (ids []uuid.UUID) {
	for id := range m.removed_Request {
		ids = append(ids, id)
	}
	return
}

// RequestIDs returns the "Request" edge IDs in the mutation.
func (m *ApprovalMutation) RequestIDs() (ids []uuid.UUID) {
	for id := range m._Request {
		ids = append(ids, id)
	}
	return
}

// ResetRequest resets all changes to the "Request" edge.
func (m *ApprovalMutation) ResetRequest() {
	m._Request = nil
	m.cleared_Request = false
	m.removed_Request = nil
}

// Where appends a list predicates to the ApprovalMutation builder.
func (m *ApprovalMutation) Where(ps ...predicate.Approval) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *ApprovalMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Approval).
func (m *ApprovalMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ApprovalMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.is_automated != nil {
		fields = append(fields, approval.FieldIsAutomated)
	}
	if m.approver != nil {
		fields = append(fields, approval.FieldApprover)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ApprovalMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case approval.FieldIsAutomated:
		return m.IsAutomated()
	case approval.FieldApprover:
		return m.Approver()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ApprovalMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case approval.FieldIsAutomated:
		return m.OldIsAutomated(ctx)
	case approval.FieldApprover:
		return m.OldApprover(ctx)
	}
	return nil, fmt.Errorf("unknown Approval field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ApprovalMutation) SetField(name string, value ent.Value) error {
	switch name {
	case approval.FieldIsAutomated:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsAutomated(v)
		return nil
	case approval.FieldApprover:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetApprover(v)
		return nil
	}
	return fmt.Errorf("unknown Approval field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ApprovalMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ApprovalMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ApprovalMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Approval numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ApprovalMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ApprovalMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ApprovalMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Approval nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ApprovalMutation) ResetField(name string) error {
	switch name {
	case approval.FieldIsAutomated:
		m.ResetIsAutomated()
		return nil
	case approval.FieldApprover:
		m.ResetApprover()
		return nil
	}
	return fmt.Errorf("unknown Approval field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ApprovalMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m._Request != nil {
		edges = append(edges, approval.EdgeRequest)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ApprovalMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case approval.EdgeRequest:
		ids := make([]ent.Value, 0, len(m._Request))
		for id := range m._Request {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ApprovalMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removed_Request != nil {
		edges = append(edges, approval.EdgeRequest)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ApprovalMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case approval.EdgeRequest:
		ids := make([]ent.Value, 0, len(m.removed_Request))
		for id := range m.removed_Request {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ApprovalMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleared_Request {
		edges = append(edges, approval.EdgeRequest)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ApprovalMutation) EdgeCleared(name string) bool {
	switch name {
	case approval.EdgeRequest:
		return m.cleared_Request
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ApprovalMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Approval unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ApprovalMutation) ResetEdge(name string) error {
	switch name {
	case approval.EdgeRequest:
		m.ResetRequest()
		return nil
	}
	return fmt.Errorf("unknown Approval edge %s", name)
}

// ProjectMutation represents an operation that mutates the Project nodes in the graph.
type ProjectMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	name             *string
	clearedFields    map[string]struct{}
	_Requests        map[uuid.UUID]struct{}
	removed_Requests map[uuid.UUID]struct{}
	cleared_Requests bool
	done             bool
	oldValue         func(context.Context) (*Project, error)
	predicates       []predicate.Project
}

var _ ent.Mutation = (*ProjectMutation)(nil)

// projectOption allows management of the mutation configuration using functional options.
type projectOption func(*ProjectMutation)

// newProjectMutation creates new mutation for the Project entity.
func newProjectMutation(c config, op Op, opts ...projectOption) *ProjectMutation {
	m := &ProjectMutation{
		config:        c,
		op:            op,
		typ:           TypeProject,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProjectID sets the ID field of the mutation.
func withProjectID(id uuid.UUID) projectOption {
	return func(m *ProjectMutation) {
		var (
			err   error
			once  sync.Once
			value *Project
		)
		m.oldValue = func(ctx context.Context) (*Project, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Project.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProject sets the old Project of the mutation.
func withProject(node *Project) projectOption {
	return func(m *ProjectMutation) {
		m.oldValue = func(context.Context) (*Project, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProjectMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProjectMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Project entities.
func (m *ProjectMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProjectMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProjectMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Project.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ProjectMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ProjectMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ProjectMutation) ResetName() {
	m.name = nil
}

// AddRequestIDs adds the "Requests" edge to the Request entity by ids.
func (m *ProjectMutation) AddRequestIDs(ids ...uuid.UUID) {
	if m._Requests == nil {
		m._Requests = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m._Requests[ids[i]] = struct{}{}
	}
}

// ClearRequests clears the "Requests" edge to the Request entity.
func (m *ProjectMutation) ClearRequests() {
	m.cleared_Requests = true
}

// RequestsCleared reports if the "Requests" edge to the Request entity was cleared.
func (m *ProjectMutation) RequestsCleared() bool {
	return m.cleared_Requests
}

// RemoveRequestIDs removes the "Requests" edge to the Request entity by IDs.
func (m *ProjectMutation) RemoveRequestIDs(ids ...uuid.UUID) {
	if m.removed_Requests == nil {
		m.removed_Requests = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m._Requests, ids[i])
		m.removed_Requests[ids[i]] = struct{}{}
	}
}

// RemovedRequests returns the removed IDs of the "Requests" edge to the Request entity.
func (m *ProjectMutation) RemovedRequestsIDs() (ids []uuid.UUID) {
	for id := range m.removed_Requests {
		ids = append(ids, id)
	}
	return
}

// RequestsIDs returns the "Requests" edge IDs in the mutation.
func (m *ProjectMutation) RequestsIDs() (ids []uuid.UUID) {
	for id := range m._Requests {
		ids = append(ids, id)
	}
	return
}

// ResetRequests resets all changes to the "Requests" edge.
func (m *ProjectMutation) ResetRequests() {
	m._Requests = nil
	m.cleared_Requests = false
	m.removed_Requests = nil
}

// Where appends a list predicates to the ProjectMutation builder.
func (m *ProjectMutation) Where(ps ...predicate.Project) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *ProjectMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Project).
func (m *ProjectMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProjectMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, project.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProjectMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case project.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProjectMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case project.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Project field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProjectMutation) SetField(name string, value ent.Value) error {
	switch name {
	case project.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown Project field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProjectMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProjectMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProjectMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Project numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProjectMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProjectMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProjectMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Project nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProjectMutation) ResetField(name string) error {
	switch name {
	case project.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown Project field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProjectMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m._Requests != nil {
		edges = append(edges, project.EdgeRequests)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProjectMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case project.EdgeRequests:
		ids := make([]ent.Value, 0, len(m._Requests))
		for id := range m._Requests {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProjectMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removed_Requests != nil {
		edges = append(edges, project.EdgeRequests)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProjectMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case project.EdgeRequests:
		ids := make([]ent.Value, 0, len(m.removed_Requests))
		for id := range m.removed_Requests {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProjectMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleared_Requests {
		edges = append(edges, project.EdgeRequests)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProjectMutation) EdgeCleared(name string) bool {
	switch name {
	case project.EdgeRequests:
		return m.cleared_Requests
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProjectMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Project unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProjectMutation) ResetEdge(name string) error {
	switch name {
	case project.EdgeRequests:
		m.ResetRequests()
		return nil
	}
	return fmt.Errorf("unknown Project edge %s", name)
}

// RequestMutation represents an operation that mutates the Request nodes in the graph.
type RequestMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	_type             *string
	requested_by      *string
	spec              *schema.RequestSpec
	clearedFields     map[string]struct{}
	_Project          *uuid.UUID
	cleared_Project   bool
	_Service          *uuid.UUID
	cleared_Service   bool
	_Approvals        map[uuid.UUID]struct{}
	removed_Approvals map[uuid.UUID]struct{}
	cleared_Approvals bool
	done              bool
	oldValue          func(context.Context) (*Request, error)
	predicates        []predicate.Request
}

var _ ent.Mutation = (*RequestMutation)(nil)

// requestOption allows management of the mutation configuration using functional options.
type requestOption func(*RequestMutation)

// newRequestMutation creates new mutation for the Request entity.
func newRequestMutation(c config, op Op, opts ...requestOption) *RequestMutation {
	m := &RequestMutation{
		config:        c,
		op:            op,
		typ:           TypeRequest,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRequestID sets the ID field of the mutation.
func withRequestID(id uuid.UUID) requestOption {
	return func(m *RequestMutation) {
		var (
			err   error
			once  sync.Once
			value *Request
		)
		m.oldValue = func(ctx context.Context) (*Request, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Request.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRequest sets the old Request of the mutation.
func withRequest(node *Request) requestOption {
	return func(m *RequestMutation) {
		m.oldValue = func(context.Context) (*Request, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RequestMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RequestMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Request entities.
func (m *RequestMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RequestMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RequestMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Request.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetType sets the "type" field.
func (m *RequestMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *RequestMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *RequestMutation) ResetType() {
	m._type = nil
}

// SetRequestedBy sets the "requested_by" field.
func (m *RequestMutation) SetRequestedBy(s string) {
	m.requested_by = &s
}

// RequestedBy returns the value of the "requested_by" field in the mutation.
func (m *RequestMutation) RequestedBy() (r string, exists bool) {
	v := m.requested_by
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestedBy returns the old "requested_by" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldRequestedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestedBy: %w", err)
	}
	return oldValue.RequestedBy, nil
}

// ResetRequestedBy resets all changes to the "requested_by" field.
func (m *RequestMutation) ResetRequestedBy() {
	m.requested_by = nil
}

// SetSpec sets the "spec" field.
func (m *RequestMutation) SetSpec(ss schema.RequestSpec) {
	m.spec = &ss
}

// Spec returns the value of the "spec" field in the mutation.
func (m *RequestMutation) Spec() (r schema.RequestSpec, exists bool) {
	v := m.spec
	if v == nil {
		return
	}
	return *v, true
}

// OldSpec returns the old "spec" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldSpec(ctx context.Context) (v schema.RequestSpec, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSpec is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSpec requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSpec: %w", err)
	}
	return oldValue.Spec, nil
}

// ResetSpec resets all changes to the "spec" field.
func (m *RequestMutation) ResetSpec() {
	m.spec = nil
}

// SetProjectID sets the "Project" edge to the Project entity by id.
func (m *RequestMutation) SetProjectID(id uuid.UUID) {
	m._Project = &id
}

// ClearProject clears the "Project" edge to the Project entity.
func (m *RequestMutation) ClearProject() {
	m.cleared_Project = true
}

// ProjectCleared reports if the "Project" edge to the Project entity was cleared.
func (m *RequestMutation) ProjectCleared() bool {
	return m.cleared_Project
}

// ProjectID returns the "Project" edge ID in the mutation.
func (m *RequestMutation) ProjectID() (id uuid.UUID, exists bool) {
	if m._Project != nil {
		return *m._Project, true
	}
	return
}

// ProjectIDs returns the "Project" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ProjectID instead. It exists only for internal usage by the builders.
func (m *RequestMutation) ProjectIDs() (ids []uuid.UUID) {
	if id := m._Project; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetProject resets all changes to the "Project" edge.
func (m *RequestMutation) ResetProject() {
	m._Project = nil
	m.cleared_Project = false
}

// SetServiceID sets the "Service" edge to the Service entity by id.
func (m *RequestMutation) SetServiceID(id uuid.UUID) {
	m._Service = &id
}

// ClearService clears the "Service" edge to the Service entity.
func (m *RequestMutation) ClearService() {
	m.cleared_Service = true
}

// ServiceCleared reports if the "Service" edge to the Service entity was cleared.
func (m *RequestMutation) ServiceCleared() bool {
	return m.cleared_Service
}

// ServiceID returns the "Service" edge ID in the mutation.
func (m *RequestMutation) ServiceID() (id uuid.UUID, exists bool) {
	if m._Service != nil {
		return *m._Service, true
	}
	return
}

// ServiceIDs returns the "Service" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ServiceID instead. It exists only for internal usage by the builders.
func (m *RequestMutation) ServiceIDs() (ids []uuid.UUID) {
	if id := m._Service; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetService resets all changes to the "Service" edge.
func (m *RequestMutation) ResetService() {
	m._Service = nil
	m.cleared_Service = false
}

// AddApprovalIDs adds the "Approvals" edge to the Approval entity by ids.
func (m *RequestMutation) AddApprovalIDs(ids ...uuid.UUID) {
	if m._Approvals == nil {
		m._Approvals = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m._Approvals[ids[i]] = struct{}{}
	}
}

// ClearApprovals clears the "Approvals" edge to the Approval entity.
func (m *RequestMutation) ClearApprovals() {
	m.cleared_Approvals = true
}

// ApprovalsCleared reports if the "Approvals" edge to the Approval entity was cleared.
func (m *RequestMutation) ApprovalsCleared() bool {
	return m.cleared_Approvals
}

// RemoveApprovalIDs removes the "Approvals" edge to the Approval entity by IDs.
func (m *RequestMutation) RemoveApprovalIDs(ids ...uuid.UUID) {
	if m.removed_Approvals == nil {
		m.removed_Approvals = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m._Approvals, ids[i])
		m.removed_Approvals[ids[i]] = struct{}{}
	}
}

// RemovedApprovals returns the removed IDs of the "Approvals" edge to the Approval entity.
func (m *RequestMutation) RemovedApprovalsIDs() (ids []uuid.UUID) {
	for id := range m.removed_Approvals {
		ids = append(ids, id)
	}
	return
}

// ApprovalsIDs returns the "Approvals" edge IDs in the mutation.
func (m *RequestMutation) ApprovalsIDs() (ids []uuid.UUID) {
	for id := range m._Approvals {
		ids = append(ids, id)
	}
	return
}

// ResetApprovals resets all changes to the "Approvals" edge.
func (m *RequestMutation) ResetApprovals() {
	m._Approvals = nil
	m.cleared_Approvals = false
	m.removed_Approvals = nil
}

// Where appends a list predicates to the RequestMutation builder.
func (m *RequestMutation) Where(ps ...predicate.Request) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *RequestMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Request).
func (m *RequestMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RequestMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m._type != nil {
		fields = append(fields, request.FieldType)
	}
	if m.requested_by != nil {
		fields = append(fields, request.FieldRequestedBy)
	}
	if m.spec != nil {
		fields = append(fields, request.FieldSpec)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RequestMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case request.FieldType:
		return m.GetType()
	case request.FieldRequestedBy:
		return m.RequestedBy()
	case request.FieldSpec:
		return m.Spec()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RequestMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case request.FieldType:
		return m.OldType(ctx)
	case request.FieldRequestedBy:
		return m.OldRequestedBy(ctx)
	case request.FieldSpec:
		return m.OldSpec(ctx)
	}
	return nil, fmt.Errorf("unknown Request field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestMutation) SetField(name string, value ent.Value) error {
	switch name {
	case request.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case request.FieldRequestedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestedBy(v)
		return nil
	case request.FieldSpec:
		v, ok := value.(schema.RequestSpec)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSpec(v)
		return nil
	}
	return fmt.Errorf("unknown Request field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RequestMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RequestMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Request numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RequestMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RequestMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RequestMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Request nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RequestMutation) ResetField(name string) error {
	switch name {
	case request.FieldType:
		m.ResetType()
		return nil
	case request.FieldRequestedBy:
		m.ResetRequestedBy()
		return nil
	case request.FieldSpec:
		m.ResetSpec()
		return nil
	}
	return fmt.Errorf("unknown Request field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RequestMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m._Project != nil {
		edges = append(edges, request.EdgeProject)
	}
	if m._Service != nil {
		edges = append(edges, request.EdgeService)
	}
	if m._Approvals != nil {
		edges = append(edges, request.EdgeApprovals)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RequestMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case request.EdgeProject:
		if id := m._Project; id != nil {
			return []ent.Value{*id}
		}
	case request.EdgeService:
		if id := m._Service; id != nil {
			return []ent.Value{*id}
		}
	case request.EdgeApprovals:
		ids := make([]ent.Value, 0, len(m._Approvals))
		for id := range m._Approvals {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RequestMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removed_Approvals != nil {
		edges = append(edges, request.EdgeApprovals)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RequestMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case request.EdgeApprovals:
		ids := make([]ent.Value, 0, len(m.removed_Approvals))
		for id := range m.removed_Approvals {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RequestMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.cleared_Project {
		edges = append(edges, request.EdgeProject)
	}
	if m.cleared_Service {
		edges = append(edges, request.EdgeService)
	}
	if m.cleared_Approvals {
		edges = append(edges, request.EdgeApprovals)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RequestMutation) EdgeCleared(name string) bool {
	switch name {
	case request.EdgeProject:
		return m.cleared_Project
	case request.EdgeService:
		return m.cleared_Service
	case request.EdgeApprovals:
		return m.cleared_Approvals
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RequestMutation) ClearEdge(name string) error {
	switch name {
	case request.EdgeProject:
		m.ClearProject()
		return nil
	case request.EdgeService:
		m.ClearService()
		return nil
	}
	return fmt.Errorf("unknown Request unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RequestMutation) ResetEdge(name string) error {
	switch name {
	case request.EdgeProject:
		m.ResetProject()
		return nil
	case request.EdgeService:
		m.ResetService()
		return nil
	case request.EdgeApprovals:
		m.ResetApprovals()
		return nil
	}
	return fmt.Errorf("unknown Request edge %s", name)
}

// ServiceMutation represents an operation that mutates the Service nodes in the graph.
type ServiceMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	name             *string
	clearedFields    map[string]struct{}
	_Requests        map[uuid.UUID]struct{}
	removed_Requests map[uuid.UUID]struct{}
	cleared_Requests bool
	done             bool
	oldValue         func(context.Context) (*Service, error)
	predicates       []predicate.Service
}

var _ ent.Mutation = (*ServiceMutation)(nil)

// serviceOption allows management of the mutation configuration using functional options.
type serviceOption func(*ServiceMutation)

// newServiceMutation creates new mutation for the Service entity.
func newServiceMutation(c config, op Op, opts ...serviceOption) *ServiceMutation {
	m := &ServiceMutation{
		config:        c,
		op:            op,
		typ:           TypeService,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withServiceID sets the ID field of the mutation.
func withServiceID(id uuid.UUID) serviceOption {
	return func(m *ServiceMutation) {
		var (
			err   error
			once  sync.Once
			value *Service
		)
		m.oldValue = func(ctx context.Context) (*Service, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Service.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withService sets the old Service of the mutation.
func withService(node *Service) serviceOption {
	return func(m *ServiceMutation) {
		m.oldValue = func(context.Context) (*Service, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ServiceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ServiceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Service entities.
func (m *ServiceMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ServiceMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ServiceMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Service.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ServiceMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ServiceMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Service entity.
// If the Service object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServiceMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ServiceMutation) ResetName() {
	m.name = nil
}

// AddRequestIDs adds the "Requests" edge to the Request entity by ids.
func (m *ServiceMutation) AddRequestIDs(ids ...uuid.UUID) {
	if m._Requests == nil {
		m._Requests = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m._Requests[ids[i]] = struct{}{}
	}
}

// ClearRequests clears the "Requests" edge to the Request entity.
func (m *ServiceMutation) ClearRequests() {
	m.cleared_Requests = true
}

// RequestsCleared reports if the "Requests" edge to the Request entity was cleared.
func (m *ServiceMutation) RequestsCleared() bool {
	return m.cleared_Requests
}

// RemoveRequestIDs removes the "Requests" edge to the Request entity by IDs.
func (m *ServiceMutation) RemoveRequestIDs(ids ...uuid.UUID) {
	if m.removed_Requests == nil {
		m.removed_Requests = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m._Requests, ids[i])
		m.removed_Requests[ids[i]] = struct{}{}
	}
}

// RemovedRequests returns the removed IDs of the "Requests" edge to the Request entity.
func (m *ServiceMutation) RemovedRequestsIDs() (ids []uuid.UUID) {
	for id := range m.removed_Requests {
		ids = append(ids, id)
	}
	return
}

// RequestsIDs returns the "Requests" edge IDs in the mutation.
func (m *ServiceMutation) RequestsIDs() (ids []uuid.UUID) {
	for id := range m._Requests {
		ids = append(ids, id)
	}
	return
}

// ResetRequests resets all changes to the "Requests" edge.
func (m *ServiceMutation) ResetRequests() {
	m._Requests = nil
	m.cleared_Requests = false
	m.removed_Requests = nil
}

// Where appends a list predicates to the ServiceMutation builder.
func (m *ServiceMutation) Where(ps ...predicate.Service) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *ServiceMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Service).
func (m *ServiceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ServiceMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, service.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ServiceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case service.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ServiceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case service.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Service field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ServiceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case service.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown Service field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ServiceMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ServiceMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ServiceMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Service numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ServiceMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ServiceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ServiceMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Service nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ServiceMutation) ResetField(name string) error {
	switch name {
	case service.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown Service field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ServiceMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m._Requests != nil {
		edges = append(edges, service.EdgeRequests)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ServiceMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case service.EdgeRequests:
		ids := make([]ent.Value, 0, len(m._Requests))
		for id := range m._Requests {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ServiceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removed_Requests != nil {
		edges = append(edges, service.EdgeRequests)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ServiceMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case service.EdgeRequests:
		ids := make([]ent.Value, 0, len(m.removed_Requests))
		for id := range m.removed_Requests {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ServiceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleared_Requests {
		edges = append(edges, service.EdgeRequests)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ServiceMutation) EdgeCleared(name string) bool {
	switch name {
	case service.EdgeRequests:
		return m.cleared_Requests
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ServiceMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Service unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ServiceMutation) ResetEdge(name string) error {
	switch name {
	case service.EdgeRequests:
		m.ResetRequests()
		return nil
	}
	return fmt.Errorf("unknown Service edge %s", name)
}
