# This Dockerfile is written for use with goreleaser
FROM gcr.io/distroless/base-debian10

# Copy the static executable built by goreleaser
COPY coastline /coastline

# Run as unprivileged user
USER nonroot:nonroot

ENTRYPOINT ["/coastline"]
CMD ["--help"]