name: ci
on:
  # Run this workflow on pushes, tags or PRs on main
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.11
          cache: "npm"
          cache-dependency-path: ui/package-lock.json
      - name: Frontend
        run: |
          npm ci
          npm run build --if-present
        working-directory: ./ui
      - name: Build
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: build --snapshot --single-target
      - name: Test
        run: go test -v -failfast ./...
      #
      # Release steps
      #
      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
